"""empty message

Revision ID: d11b8ad94712
Revises: 
Create Date: 2021-02-09 00:12:52.633985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11b8ad94712'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('data_nasc', sa.String(length=10), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('numero_cartao', sa.String(length=16), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cartao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
